version: '2.1'
services:
  

  ventilator:
    build: ./ventilator
    restart: always

    ports:
      - 5555:5555
    container_name: ventilator
    volumes:
      - ./ventilator/src:/app
    

  sink:
    build: ./sink
    restart: always
    ports:
      - 5556:5556
    container_name: sink
    volumes:
      - ./sink/src:/app


  spawn_worker:
    build: ./workers/
    restart: always
    volumes:
      - ./workers/src:/app
    deploy:
      replicas: 4

networks:
  default:
    name: queues